/** Voci del menu «?» in inglese: chiave = percorso italiano, valore = [etichetta, percorso nella guida inglese]. */
export const HELP_EN: Record<string, [string, string]> = {
  "guide/statistics#cosa-si-misura": ["What is measured", "guide/statistics#what-is-measured"],
  "guide/statistics#la-dashboard": ["The dashboard", "guide/statistics#the-dashboard"],
  "guide/statistics#prometheus": ["Prometheus", "guide/statistics#prometheus"],
  "guide/cache#cosa-dice-x-cache": ["What X-Cache says", "guide/cache#what-x-cache-says"],
  "guide/domains-dns#cosa-controlla-la-verifica": ["What verification checks", "guide/domains-dns#what-verification-checks"],
  "guide/domains-dns#quali-record-creare": ["Which records to create", "guide/domains-dns#which-records-to-create"],
  "guide/domains-dns#propagazione-e-tempi": ["Propagation and timing", "guide/domains-dns#propagation-and-timing"],
  "guide/domains-dns#gli-stati-di-un-dominio": ["Domain states", "guide/domains-dns#domain-states"],
  "providers/#dns": ["DNS providers", "providers/#dns"],
  "guide/troubleshooting#domini": ["Domain problems", "guide/troubleshooting#domains"],
  "guide/buckets-s3#i-campi": ["The fields", "guide/buckets-s3#the-fields"],
  "guide/buckets-s3#path-oppure-virtual-host": ["Path or virtual host", "guide/buckets-s3#path-or-virtual-host"],
  "guide/buckets-s3#permessi-minimi-sola-lettura": ["Minimum permissions (read-only)", "guide/buckets-s3#minimum-permissions-read-only"],
  "providers/#storage-s3": ["S3 providers", "providers/#s3-storage"],
  "guide/troubleshooting#bucket": ["Bucket problems", "guide/troubleshooting#buckets"],
  "guide/routes#come-si-legge": ["How to read it", "guide/routes#how-to-read-it"],
  "guide/routes#regole-di-scelta": ["Selection rules", "guide/routes#selection-rules"],
  "guide/cache#la-politica-di-cache": ["The cache policy", "guide/cache#the-cache-policy"],
  "guide/troubleshooting#instradamenti-e-file": ["Problems with files and 404", "guide/troubleshooting#routes-and-files"],
  "guide/troubleshooting": ["Troubleshooting", "guide/troubleshooting"],
  "guide/notifications#cosa-viene-notificato": ["What is notified", "guide/notifications#what-is-notified"],
  "guide/notifications#telegram": ["Telegram", "guide/notifications#telegram"],
  "guide/notifications#email-smtp": ["Email (SMTP)", "guide/notifications#email-smtp"],
  "guide/notifications#soglie-attesa-e-ripristino": ["Thresholds, delay and recovery", "guide/notifications#thresholds-delay-and-recovery"],
  "guide/upgrades-backup#aggiornare": ["Updates", "guide/upgrades-backup#upgrading"],
  "guide/upgrades-backup#backup-dal-pannello": ["Backup from the panel", "guide/upgrades-backup#backup-from-the-panel"],
  "guide/install#porte-standard": ["Standard ports", "guide/install#standard-ports"],
  "reference/environment": ["Environment variables", "reference/environment"],
  "guide/https-proxy": ["HTTPS and proxy", "guide/https-proxy"],
  "guide/users-2fa#ruoli-e-scope": ["Roles and scopes", "guide/users-2fa#roles-and-scopes"],
  "guide/users-2fa#aggiungere-un-utente": ["Adding a user", "guide/users-2fa#adding-a-user"],
  "guide/users-2fa#renderla-obbligatoria": ["Making 2FA mandatory", "guide/users-2fa#making-it-mandatory"],
  "guide/users-2fa#registro-delle-attivita": ["Activity log", "guide/users-2fa#activity-log"],
  "guide/security": ["Security", "guide/security"],
  "guide/users-2fa#verifica-in-due-passaggi-2fa": ["Turning on 2FA", "guide/users-2fa#two-step-verification-2fa"],
  "guide/users-2fa#accedere-con-la-2fa": ["Recovery codes", "guide/users-2fa#signing-in-with-2fa"],
  "guide/users-2fa#perdere-l-accesso": ["Losing access", "guide/users-2fa#losing-access"],
};
